title: 'cat /dev/urandom > blog'
description: "No idea what's happening here."
theme: minima
lang: en
show_excerpts: true

url: "https://coolduderude.github.io"
baseurl: "/blog"

plugins:
  - jekyll-seo-tag
  - jekyll-feed
